### PR TITLE
[0.4] Bump minimum PHP to 7.4

### PR DESCRIPTION
**Pull request by mbabker**
Unblocks #51

Based on https://packagist.org/packages/ratchet/rfc6455/php-stats#0.3 it would cover 75% of active consumers of this library (with PHP 7.2 and 7.3 being another 20% combined).

### CODE REVIEW

**Comment by cboden** [comment]
Given https://www.php.net/supported-versions.php I was even considering requiring 7.4. With v0.3.* keeping really old BC compatibility with a few updates soon, I'd be ok with making a bigger jump for v0.4. 

Thoughts?

**Comment by mbabker** [comment]
That works too.  Originally I was going to jump straight to 7.4, but there's still a sizeable chunk of users on 7.2 and 7.3 so I broadened it just a bit.

**Comment by cboden** [comment]
Thanks Michael. I re-targeted against the v0.4 branch. There's a conflict since we corrected some stuff for v0.3.1. 

Shall we drop Guzzle 1 support?

**Comment by mbabker** [comment]
> There's a conflict since we corrected some stuff for v0.3.1.

That's fixed.

> Shall we drop Guzzle 1 support?

I wouldn't just yet.  The 1.8 branch just got a new release a couple of months ago and the 1.x installs are still 2:1 over the 2.x installs, so it sounds like the long tail of consumers of that package might take a little while to catch up on it.

**Review by cboden — APPROVED** [review]

**Comment by cboden** [comment]
> That works too. Originally I was going to jump straight to 7.4, but there's still a sizeable chunk of users on 7.2 and 7.3 so I broadened it just a bit.

v0.3.1 can still be used by users who are using unsupported versions.

**Pull request merged**
