### PR TITLE
[0.4] Use latest PHPUnit and modernize test code

### LINKED ISSUE #58: Bump up testing
* Add PHP 8 and 8.1 to GitHub Actions CI testing
* Update PHPUnit version used to test

### PR DESCRIPTION
**Pull request by mbabker**
Closes #58

- Bumps the PHPUnit requirement to 9.5
- Adds CI for PHP 8 and 8.1
- Modernizes test code (updated PHPUnit config, updates PHPUnit usage to account for deprecations/removals, starts adding typehints, and misc. code structure tweaks)

### CODE REVIEW

**Review by mbonneau — APPROVED** [review]

**Comment by cboden** [comment]
The Autobahn test suite tests are coming up as "Risky". Can this be fixed?

```
1) Ratchet\RFC6455\Test\AbResultsTest::testAutobahnClientResults
This test does not have a @covers annotation but is expected to have one
```

and 

```
1) Ratchet\RFC6455\Test\AbResultsTest::testAutobahnServerResults
This test does not have a @covers annotation but is expected to have one
```

**Comment by mbabker** [comment]
> The Autobahn test suite tests are coming up as "Risky". Can this be fixed?

Not without turning off the `forceCoversAnnotation` PHPUnit config, I think.  I don't have Docker set up on this system so I can't run things to check it myself, but it looks like this test class isn't a pure unit test class and conflicts with that config directive because it's not directly covering any of the code in the package, but more of a functional/integration test class and you wouldn't necessarily annotate `@covers` on these types of tests as by design they could cover nothing or anything/everything.

**Comment by cboden** [comment]
Yeah, it's definitely an integration test. The Action works by running the Autobahn client+server test suites and generating an output report in JSON. Then PHPUnit runs and checks the report generated by Autobahn and will pass if all passed or fail if one failed, in addition to running actual PHPUnit unit tests.

**Comment by mbabker** [comment]
Turns out there is a `@coversNothing` annotation which will work well enough for the `AbResultsTest`.  I also wiped all the method level `@covers` annotations since declaring them at the class level will work well enough.

**Review by cboden — APPROVED** [review]

**Comment by cboden** [comment]
Awesome, thanks Michael!

**Pull request merged**
